In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("customer.csv")

In [3]:
df.sample(5)

    age  gender   review education purchased
17   22  Female     Poor        UG       Yes
44   77  Female  Average        UG        No
28   48    Male     Poor    School        No
40   39    Male     Good    School        No
35   74    Male     Poor    School       Yes

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

FileNotFoundError: [Errno 2] No such file or directory: 'your_dataset.csv'

In [7]:
X_train

NameError: name 'X_train' is not defined